# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'w.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 576)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 241, 52, 255), stop:1 rgba(255, 111, 111, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.b_sl_pod = QtWidgets.QPushButton(self.centralwidget)
        self.b_sl_pod.setGeometry(QtCore.QRect(0, 470, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.b_sl_pod.setFont(font)
        self.b_sl_pod.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.153409 rgba(85, 85, 255, 255), stop:1 rgba(255, 65, 0, 255));\n"
"border-radius: 30px;\n"
"border: 5px solid rgb(0, 85, 127);\n"
"color: rgb(255, 255, 0);")
        self.b_sl_pod.setObjectName("b_sl_pod")
        self.txt_lang = QtWidgets.QLabel(self.centralwidget)
        self.txt_lang.setGeometry(QtCore.QRect(360, 420, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.txt_lang.setFont(font)
        self.txt_lang.setStyleSheet("background-color: rgb(255, 153, 64);\n"
"border-radius: 10px;\n"
"border: 5px solid rgb(0, 85, 127);\n"
"color: rgb(0, 85, 127);\n"
"")
        self.txt_lang.setObjectName("txt_lang")
        self.vibor_lang = QtWidgets.QComboBox(self.centralwidget)
        self.vibor_lang.setGeometry(QtCore.QRect(590, 420, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.vibor_lang.setFont(font)
        self.vibor_lang.setStyleSheet("background-color: rgb(255, 153, 64);\n"
"border-radius: 10px;\n"
"border: 5px solid rgb(0, 85, 127);\n"
"color: rgb(0, 85, 127);\n"
"")
        self.vibor_lang.setMaxVisibleItems(10)
        self.vibor_lang.setObjectName("vibor_lang")
        self.vibor_lang.addItem("")
        self.vibor_lang.addItem("")
        self.vibor_lang.addItem("")
        self.vibor_lang.addItem("")
        self.b_smn_lang = QtWidgets.QPushButton(self.centralwidget)
        self.b_smn_lang.setGeometry(QtCore.QRect(870, 430, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.b_smn_lang.setFont(font)
        self.b_smn_lang.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.153409 rgba(85, 85, 255, 255), stop:1 rgba(255, 65, 0, 255));\n"
"border-radius: 40px;\n"
"border: 5px solid rgb(0, 85, 127);\n"
"color: rgb(255, 255, 0);")
        self.b_smn_lang.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../files_to_del/button_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_smn_lang.setIcon(icon)
        self.b_smn_lang.setIconSize(QtCore.QSize(64, 64))
        self.b_smn_lang.setObjectName("b_smn_lang")
        self.text_toch = QtWidgets.QLabel(self.centralwidget)
        self.text_toch.setGeometry(QtCore.QRect(0, 310, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.text_toch.setFont(font)
        self.text_toch.setStyleSheet("background-color: rgb(255, 153, 64);\n"
"border-radius: 10px;\n"
"border: 5px solid rgb(0, 85, 127);\n"
"color: rgb(0, 85, 127);\n"
"")
        self.text_toch.setObjectName("text_toch")
        self.txt_vvod = QtWidgets.QLabel(self.centralwidget)
        self.txt_vvod.setGeometry(QtCore.QRect(0, 0, 191, 81))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.txt_vvod.setFont(font)
        self.txt_vvod.setStyleSheet("background-color: rgb(255, 153, 64);\n"
"border-radius: 10px;\n"
"border: 5px solid rgb(0, 85, 127);\n"
"color: rgb(0, 85, 127);\n"
"")
        self.txt_vvod.setObjectName("txt_vvod")
        self.text_otvet = QtWidgets.QLabel(self.centralwidget)
        self.text_otvet.setGeometry(QtCore.QRect(0, 180, 191, 81))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.text_otvet.setFont(font)
        self.text_otvet.setStyleSheet("background-color: rgb(255, 153, 64);\n"
"border-radius: 10px;\n"
"border: 5px solid rgb(0, 85, 127);\n"
"color: rgb(0, 85, 127);\n"
"\n"
"")
        self.text_otvet.setObjectName("text_otvet")
        self.b_vyp = QtWidgets.QPushButton(self.centralwidget)
        self.b_vyp.setGeometry(QtCore.QRect(400, 100, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.b_vyp.setFont(font)
        self.b_vyp.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.153409 rgba(85, 85, 255, 255), stop:1 rgba(255, 65, 0, 255));\n"
"border-radius: 30px;\n"
"border: 5px solid rgb(0, 85, 127);\n"
"color: rgb(255, 255, 0);")
        self.b_vyp.setObjectName("b_vyp")
        self.vvod_otvet = QtWidgets.QTextEdit(self.centralwidget)
        self.vvod_otvet.setGeometry(QtCore.QRect(190, 0, 821, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.vvod_otvet.setFont(font)
        self.vvod_otvet.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 5px solid rgb(0, 85, 127);")
        self.vvod_otvet.setObjectName("vvod_otvet")
        self.vvod_toch = QtWidgets.QTextEdit(self.centralwidget)
        self.vvod_toch.setGeometry(QtCore.QRect(220, 310, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.vvod_toch.setFont(font)
        self.vvod_toch.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 5px solid rgb(0, 85, 127);")
        self.vvod_toch.setObjectName("vvod_toch")
        self.vivid_otvet = QtWidgets.QTextBrowser(self.centralwidget)
        self.vivid_otvet.setGeometry(QtCore.QRect(190, 180, 821, 81))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.vivid_otvet.setFont(font)
        self.vivid_otvet.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 5px solid rgb(0, 85, 127);")
        self.vivid_otvet.setObjectName("vivid_otvet")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b_sl_pod.setText(_translate("MainWindow", "Служба поддержки"))
        self.txt_lang.setText(_translate("MainWindow", "Язык:"))
        self.vibor_lang.setItemText(0, _translate("MainWindow", "Русский"))
        self.vibor_lang.setItemText(1, _translate("MainWindow", "English"))
        self.vibor_lang.setItemText(2, _translate("MainWindow", "中文"))
        self.vibor_lang.setItemText(3, _translate("MainWindow", "Español"))
        self.text_toch.setText(_translate("MainWindow", "Точность:"))
        self.txt_vvod.setText(_translate("MainWindow", "Ввод:"))
        self.text_otvet.setText(_translate("MainWindow", "Ответ:"))
        self.b_vyp.setText(_translate("MainWindow", "Выполнить"))
